name: chess
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  chess: ^0.8.1
  provider: ^6.1.5
  audioplayers: ^6.1.2
  confetti: ^0.8.0
  collection: ^1.19.0
  flutter/services: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/board.png
    - assets/wq.png
    - assets/wn.png
    - assets/wb.png
    - assets/pieces/cburnett/
    - assets/sounds/
